on:
  push:
    branches: [ "ci/cd" ]
jobs:
  # iOS build 
  ios-build:
    name: iOS CI/CD Build
    permissions: write-all
    runs-on: macos-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - uses: expo/expo-github-action@v5
        with:
          expo-version: latest
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}

      - name: Setup EAS
        run: npm install -g eas-cli 
        working-directory: ./EventPlanner

      - name: Install dependencies
        run: npm install && npm install --save dotenv && npm i @react-native-firebase/app
        working-directory: ./EventPlanner

      - name: Build iOS app
        run: eas build --platform ios --local --profile development
        working-directory: ./EventPlanner


  # Android build 
  android-build:
    name: Android CI/CD Build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3


      - uses: expo/expo-github-action@v5
        with:
          expo-version: latest
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}

      - name: Setup EAS
        run: npm install -g eas-cli 
        working-directory: ./EventPlanner

      - name: Install dependencies
        run: npm install && npm install --save dotenv && npm i @react-native-firebase/app
        working-directory: ./EventPlanner

      - name: Build Android APK Bundle
        run: eas build --platform android
        working-directory: ./EventPlanner
