on:
  push:
    branches: [ "ci/cd" ]
jobs:
  # ios-build:
  #   name: iOS CI/CD Build
  #   permissions: write-all
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 16.x
  #     - uses: actions/setup-java@v1.4.3
  #       with:
  #         java-version: '9.0.4' # The JDK version to make available on the path.
  #         java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
  #         architecture: x64 # (x64 or x86) - defaults to x64
  #     - uses: sinoru/actions-setup-xcode@v1.1.2
  #       with:
  #         xcode-version: '11.2.1' # Exact version of a Xcode version to use
  #         apple-id: ${{ secrets.EXPO_APPLE_ID }} # Apple ID to download from Apple Developer when Xcode not available in local
  #         apple-id-password: ${{ secrets.EXPO_APPLE_PASSWORD }}
  #     - uses: expo/expo-github-action@v5
  #       with:
  #         expo-version: latest
  #         expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
  #         expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
  #     - name: Setup EAS
  #       run: npm install -g eas-cli 
  #     - name: Install deps
  #       run: yarn install
  #     - name: Build iOS app
  #       run: eas build --platform ios
  #       env:
  #           EXPO_APPLE_ID: ${{secrets.EXPO_APPLE_ID}}
  #           EXPO_APPLE_ID_PASSWORD: ${{secrets.EXPO_APPLE_PASSWORD}} 

  android-build:
    name: Android CI/CD Build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3


      - uses: expo/expo-github-action@v5
        with:
          expo-version: latest
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Setup EAS
        run: npm install -g eas-cli 

      - name: Install dependencies
        run: yarn install && npm install && npm install --save dotenv && npm i @react-native-firebase/app

      - name: Build Android APK Bundle
        run: cd EventPlanner && eas build --platform android
