on:
  push:
    branches: ["ci/cd"]

jobs:
  general-build:
    name: General Build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - uses: expo/expo-github-action@v5
        with:
          expo-version: latest
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}

      - name: Setup EAS
        run: npm install -g eas-cli
        working-directory: ./EventPlanner

      - name: Install dependencies
        run: npm install && npm install --save dotenv && npm i @react-native-firebase/app
        working-directory: ./EventPlanner

      - name: Build
        run: eas build --platform all
        working-directory: ./EventPlanner
